// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hastane.Data;

#nullable disable

namespace hastane.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609124443_FixPatientRelation")]
    partial class FixPatientRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("hastane.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("hastane.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "İç hastalıkları tanı ve tedavisi",
                            ImageUrl = "/img/departments/internal.jpg",
                            Name = "Dahiliye"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kulak, burun ve boğaz hastalıkları",
                            ImageUrl = "/img/departments/ent.jpg",
                            Name = "KBB"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kalp ve damar hastalıkları",
                            ImageUrl = "/img/departments/cardiology.jpg",
                            Name = "Kardiyoloji"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cilt hastalıkları tanı ve tedavisi",
                            ImageUrl = "/img/departments/dermatology.jpg",
                            Name = "Dermatoloji"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Göz ve görme ile ilgili hastalıklar",
                            ImageUrl = "/img/departments/ophthalmology.jpg",
                            Name = "Göz Hastalıkları"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kas ve iskelet sistemi hastalıkları",
                            ImageUrl = "/img/departments/orthopedics.jpg",
                            Name = "Ortopedi"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sinir sistemi hastalıkları",
                            ImageUrl = "/img/departments/neurology.jpg",
                            Name = "Nöroloji"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ruh sağlığı ve hastalıkları",
                            ImageUrl = "/img/departments/psychiatry.jpg",
                            Name = "Psikiyatri"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Üriner sistem hastalıkları",
                            ImageUrl = "/img/departments/urology.jpg",
                            Name = "Üroloji"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Kadın üreme sistemi ve gebelik takibi",
                            ImageUrl = "/img/departments/gynecology.jpg",
                            Name = "Kadın Hastalıkları ve Doğum"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Hormon ve metabolizma hastalıkları",
                            ImageUrl = "/img/departments/endocrinology.jpg",
                            Name = "Endokrinoloji"
                        });
                });

            modelBuilder.Entity("hastane.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dahiliye uzmanı olarak 10 yılı aşkın deneyime sahip",
                            Email = "ahmet.yilmaz@medivita.com",
                            ImageUrl = "/img/doctors/doctor1.jpg",
                            Name = "Dr. Ahmet Yılmaz",
                            Password = "test123",
                            Specialty = "Dahiliye"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kulak Burun Boğaz hastalıkları konusunda uzman hekim",
                            Email = "mehmet.kaya@medivita.com",
                            ImageUrl = "/img/doctors/doctor3.jpg",
                            Name = "Dr. Mehmet Kaya",
                            Password = "test123",
                            Specialty = "KBB"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kalp ve damar hastalıkları konusunda deneyimli uzman",
                            Email = "ali.ozturk@medivita.com",
                            ImageUrl = "/img/doctors/doctor2.jpg",
                            Name = "Dr. Ali Öztürk",
                            Password = "test123",
                            Specialty = "Kardiyoloji"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cilt hastalıkları ve estetik dermatoloji uzmanı",
                            Email = "can.yucel@medivita.com",
                            ImageUrl = "/img/doctors/doctor7.jpg",
                            Name = "Dr. Can Yücel",
                            Password = "test123",
                            Specialty = "Dermatoloji"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Göz hastalıkları ve cerrahi operasyonlar konusunda uzman",
                            Email = "ece.sahin@medivita.com",
                            ImageUrl = "/img/doctors/doctor9.jpg",
                            Name = "Dr. Ece Şahin",
                            Password = "test123",
                            Specialty = "Göz Hastalıkları"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ortopedi ve travmatoloji uzmanı",
                            Email = "gamze.ozkan@medivita.com",
                            ImageUrl = "/img/doctors/doctor11.jpg",
                            Name = "Dr. Gamze Özkan",
                            Password = "test123",
                            Specialty = "Ortopedi"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nörolojik hastalıklar konusunda deneyimli uzman",
                            Email = "irem.dogan@medivita.com",
                            ImageUrl = "/img/doctors/doctor13.jpg",
                            Name = "Dr. İrem Doğan",
                            Password = "test123",
                            Specialty = "Nöroloji"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Psikiyatri ve psikoterapi konusunda uzman hekim",
                            Email = "kemal.tunc@medivita.com",
                            ImageUrl = "/img/doctors/doctor15.jpg",
                            Name = "Dr. Kemal Tunç",
                            Password = "test123",
                            Specialty = "Psikiyatri"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Üroloji ve androloji uzmanı",
                            Email = "murat.ersoy@medivita.com",
                            ImageUrl = "/img/doctors/doctor17.jpg",
                            Name = "Dr. Murat Ersoy",
                            Password = "test123",
                            Specialty = "Üroloji"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Kadın hastalıkları ve doğum uzmanı",
                            Email = "osman.kara@medivita.com",
                            ImageUrl = "/img/doctors/doctor19.jpg",
                            Name = "Dr. Osman Kara",
                            Password = "test123",
                            Specialty = "Kadın Hastalıkları ve Doğum"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Endokrinoloji ve metabolizma hastalıkları uzmanı",
                            Email = "riza.altin@medivita.com",
                            ImageUrl = "/img/doctors/doctor21.jpg",
                            Name = "Dr. Rıza Altın",
                            Password = "test123",
                            Specialty = "Endokrinoloji"
                        });
                });

            modelBuilder.Entity("hastane.Models.DoctorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailability");
                });

            modelBuilder.Entity("hastane.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("hastane.Models.Appointment", b =>
                {
                    b.HasOne("hastane.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hastane.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("hastane.Models.Doctor", b =>
                {
                    b.HasOne("hastane.Models.Department", null)
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("hastane.Models.DoctorAvailability", b =>
                {
                    b.HasOne("hastane.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("hastane.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("hastane.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("hastane.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
